name: queryflow
description: "Queryflow is a lightweight and flexible Dart package designed to simplify the process of building and executing SQL queries."
version: 0.1.1
homepage: https://github.com/RafaelBarbosatec/queryflow

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mysql_dart: ^1.0.0
  

dev_dependencies:
  test: any
  flutter_lints: ^5.0.0

