name: Test and Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Intall dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Analyze
        run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Intall dart
        uses: dart-lang/setup-dart@v1
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'boleiro'
          mysql user: 'admin'
          mysql password: '12345678'
      - name: Start PostgreSQL
        uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: '14'
          postgresql db: 'boleiro'
          postgresql user: 'admin'
          postgresql password: '12345678'
      - name: Test
        run: dart test